BMV2_SWITCH_EXE = simple_switch_grpc
TOFINO_SWITCH = tofino_grpc
TOFINO_ADDR = 192.168.105.241

NO_P4 = true
P4C_ARGS = --p4runtime-file $(basename $@).p4info --p4runtime-format text

include ../../utils/Makefile
