FROM ubuntu:16.04
#FROM p4lang/third-party:stable
LABEL maintainer="Xiao Wang <xiao.wang2@northwestern.edu.com>"
LABEL maintainer="Se-young Yu <young.yu@northwestern.edu.com>"

ADD root-bootstrap.sh /root/root-bootstrap.sh
RUN ./root/root-bootstrap.sh
RUN echo "done"
